const express = require('express');
const helmet = require('helmet');
const ProjectRouter = require('./projects/projectsRouter.js');
const ResourceRouter = require('./resources/resource-router.js');
const server = express();
server.use(helmet());
server.use(express.json());
server.use('/projects', ProjectRouter);
server.use('/resources', ResourceRouter);
module.exports = server;